"""initial schema

Revision ID: 4d5d049c77de
Revises: 
Create Date: 2026-02-23 09:02:30.472910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5d049c77de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('phase', sa.Enum('lobby', 'card_creation', 'playing', 'final_round', 'finished', name='gamephase'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('current_round_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['current_round_id'], ['rounds.id'], name='fk_game_current_round', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_code'), ['code'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('player', 'spectator', name='playerrole'), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('join_order', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'display_name', name='uq_game_display_name')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_session_token'), ['session_token'], unique=True)

    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('holder_id', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.Enum('start', 'stop', 'continue', name='cardtype'), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_played', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['holder_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_holder_id'), ['holder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_is_played'), ['is_played'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('adjective', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.Enum('submitting', 'revealed', 'complete', name='roundphase'), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('winning_card_id', sa.Integer(), nullable=True),
    sa.Column('is_final_round', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winning_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_game_id'), ['game_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'player_id', name='uq_round_player_submission')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_round_id'), ['round_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'voter_id', name='uq_round_voter_vote')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_round_id'), ['round_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_round_id'))

    op.drop_table('votes')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_round_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_game_id'))

    op.drop_table('rounds')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_is_played'))
        batch_op.drop_index(batch_op.f('ix_cards_holder_id'))
        batch_op.drop_index(batch_op.f('ix_cards_game_id'))

    op.drop_table('cards')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_session_token'))
        batch_op.drop_index(batch_op.f('ix_players_game_id'))

    op.drop_table('players')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_code'))

    op.drop_table('games')
    # ### end Alembic commands ###
